#+title: Synthetic Population Generation Project
#+description: Synthetic population generation is the process of combining multiple socioeonomic and datasets from various sources and at different granularity, and downscaling them to an individual level. In this project, an aggregated data is provided from TransUnion, and an individual level data is provided as well. The question is to map the aggregated data into individual level data, so that the individual level data would have the features from the aggregated data. 

* Goal
  There are hundreds of features provided by the TransUnion data; however,
  due to the privacy, the data is aggregated and only statistics such as mean,
  max, min, and std are provided. The goal is to downscale a selected feature
  from the dataset and map it to an existing demographic dataset, so that the
  demographic dataset will possess the feature from the TransUnion dataset.
* Experimental
** Method  
   Before mapping the aggregated data into the individual level, the
   relationship between the two datasets should be found. Two datasets need to
   be merged in to a single one based on the postal code. By doing so, the
   correlation between each feature can be explored. 
** Preprocessing
*** Aggregated Data
    - The feature "number of trade" is selected to be mapped into the demographic
      data.
    - The variables I am interested in are "Count", "Sum", "Min", "Max", "Mean",
      "Median", and "StdDev".
    - The data is not grouped in PostalCode, instead, it is grouped in the
      street level. Fortunately, the data can be re-grouped in PostalCode level
      without any loss of accuracy. The method can be found [[http://www.burtonsys.com/climate/composite_standard_deviations.html][here]].
*** TODO Demographic Data [0/1]
    - The feature "Demographics" actually contains two separate variables, which
      are age and gender. Therefore, this feature is split into two features --
      "Age" and "Gender". 
    - Most of features are categorical, more specifically, nominal. In order to
      aggregate the individual data and merge it with the TransUnion dataset, the
      percentage of each category in a nominal feature is calculated based on
      each postal code. I have tried a few ways to do it, but the most
      efficient way is to use pandas.to_dummies() function.
    - [ ] Get random age and calculate the mean.
*** Join Two Datasets
    Two datasets were joined together based on the postal code.
** Analysis
   1. The correlation coefficients between the feature "Mean" and the rest of the
      features are calculated. 
   2. Only the features with the correlation coefficients above 0.2 or less than
      -0.2 are selected and plotted against the feature "Mean".
** TODO Downscale Aggregated Data [0/2]
  - [ ] Graphic model
  - [ ] Generated model
